paths:
  dataset_path: '/home/kli16/ISM_custom/esm_NSUBS_RWSE_LapPE/esm_LapPE/data/MSRC_21/MSRC_21_trainset_dense_noiseratio_0_5_10_n_16_32_num_01_31_LapPE.pkl'
  checkpoint_path: '/home/kli16/ISM_custom/esm_NSUBS_RWSE_LapPE/esm_LapPE/ckpt_imitationlearning/2024-03-31_12-42-48/checkpoint_54000.pth'
hyperparameters:  
  imitationlearning: true
  lr_decay: false
  T_max: 50000
  weight_decay: 0
  update_timestep: 2048
  K_epochs: 10
  eps_clip: 0.2
  gamma: 0.99
  lr: 0.0003
  batch_size: 1024 
  max_training_episodes: 1000000
  ec_policy: 1
  ec_value: 0
  ec_entropy: 0.01
